/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: battery_0_bar_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/
#include <stdint.h>
#include "ux/rasterizer.h"

static const uint8_t battery_image[40] = {
    /* row 0 */ 0x1E, 0x00,   /* ░░░████░░░ */
    /* row 1 */ 0x1E, 0x00,   /* ░░░████░░░ */
    /* row 2 */ 0xFF, 0xC0,   /* ██████████ */
    /* row 3 */ 0x80, 0x40,   /* █░░░░░░░░█ */
    /* row 4 */ 0x80, 0x40,   /* █░░░░░░░░█ */
    /* row 5 */ 0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,
                0x80, 0x40,   /* rows 3‑17 (15×) interior blank with 1‑px walls */
    /* row18 */ 0xFF, 0xC0,   /* ██████████ */
    /* row19 */ 0xFF, 0xC0    /* ██████████ */
    };

const tImage battery = { battery_image, 10, 20, 8 };

